### ISSUE TITLE
You can cut the world_map.json file down to 0.13x its original filesize, at least

### ISSUE THREAD

**Issue by AskAlice** [Melonman0/InteractiveMap#1]
first off, great combinations of technology. This is super clean!

Anyway, if you're planning on using this in production, probably best to not serve a 415kb geojson file filled with fields that you don't need.

you can see these unused fields easily with
```
mapshaper info
```

to minify this, just run

``` 
mapshaper world_map.json -filter-fields NAME -simplify 40% -filter remove-empty -clean -o new_map.json
```

you can also project it like most maps are displayed: https://en.wikipedia.org/wiki/Web_Mercator_projection

just add `-proj merc` to the commandline args

**Comment by Melonman0** [comment]
Thanks for the info! I'll try that right away!

**Comment by Melonman0** [comment]
I simplified the world_map.json and removed all the unneeded features. The file is now down to 1/4 of it's original size. I didn't want to simplify it more because some countries start losing their shape too much (i.e. Italy losing it's unique boot-shape)

Unfortunately I couldn't figure out how to get the Web Mercator projection working. It seems that when I use the "-proj merc" args, the coordinate system completely changes. I'll have to figure out how to get that working, so I'll close this and make a new issue for that.

Thanks again for the feedback @AskAlice!

**Comment by AskAlice** [comment]
@Melonman0 with -proj merc, i just divided the coordinates by something like 1000000

**Comment by Melonman0** [comment]
@AskAlice I actually figured it out how to make a map without using crazy coordinates in the millions.

In mapshaper, I just used this command line:
`-proj +proj=merc +a=55 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs`

The `+a` parameter seems to constrain the x-coordinates of the map so they are not in the millions any more. You can also add a `+b` to constrain they y-coordinates, but leaving it out seems to let mapshaper keep the correct aspect ratio. I'm not too sure what the other parameters do, but it seems to have worked for me lol.

**Comment by AskAlice** [comment]
ah neat! nice job

**Comment by AskAlice** [comment]
this could very well be a helper tool, if you implemented this code similarly to https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/SVGLoader.js, it could easily be used with things like https://github.com/react-spring/react-three-fiber/. However, I think this would be far less complicated compared to the SVGLoader since there aren't as many types of paths. Just shapes and lines.

From there it could be extended from a THREE primitive that could implement the loader such as is suggested here https://github.com/mrdoob/three.js/issues/13478
